//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autores.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbAppLibreriaEntities : DbContext
    {
        public dbAppLibreriaEntities()
            : base("name=dbAppLibreriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Libros> Libros { get; set; }
        public virtual DbSet<LibrosRelaciones> LibrosRelaciones { get; set; }
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<v_Lista_LibrosRelacion> v_Lista_LibrosRelacion { get; set; }
    }
}
